name: Vérification Markdown

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Vérifier les fichiers Markdown
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "**/*.md"
